INSERT INTO eventos( id, title, date_hour, max_participants, description, actual_participants) VALUES (default,'Conciertazo', '2023-01-10',  200,  'Madonna Tour Nations',  100)
INSERT INTO eventos( id, title, date_hour, max_participants, description, actual_participants) VALUES (default,'El Fary', '2023-01-08',  300,  'El fary ninio',  200)
INSERT INTO eventos( id, title, date_hour, max_participants, description, actual_participants) VALUES (default,'Las Ketchup', '2023-01-10',  100,  'Asere Jeee',  100)
INSERT INTO eventos( id, title, date_hour, max_participants, description, actual_participants) VALUES (default,'Las Ketchup', '2023-01-09',  100,  'Asere Jeee',  100)
INSERT INTO eventos( id, title, date_hour, max_participants, description, actual_participants) VALUES (default,'Las Ketchup', '2023-01-12',  100,  'Asere Jeee',  100)
INSERT INTO users( id, username, password) VALUES (default,'Raul', 'qwerty12345' )
