INSERT INTO eventos( id, title, date_hour, max_participants, description, actual_participants) VALUES (default,'Conciertazo', '19/05/2023-15:00h',  200,  'Madonna Tour Nations',  100)
INSERT INTO eventos( id, title, date_hour, max_participants, description, actual_participants) VALUES (default,'El Fary', '11/09/2023-15:00h',  300,  'El fary ninio',  200)
INSERT INTO eventos( id, title, date_hour, max_participants, description, actual_participants) VALUES (default,'Las Ketchup', '09/12/2023-15:00h',  100,  'Asere Jeee',  100)
INSERT INTO eventos( id, title, date_hour, max_participants, description, actual_participants) VALUES (default,'Las Ketchup', '09/12/2023-15:00h',  100,  'Asere Jeee',  100)
INSERT INTO eventos( id, title, date_hour, max_participants, description, actual_participants) VALUES (default,'Las Ketchup', '09/12/2023-15:00h',  100,  'Asere Jeee',  100)
INSERT INTO users( id, username, password) VALUES (default,'Raul', 'qwerty12345' )
