
INSERT INTO events( id, title, style, date_hour, max_participants, description, actual_participants) VALUES (default,'Conciertazo', 'rock', '2023-01-12',  300,  'Madonna Tour Nations',  100)
INSERT INTO events( id, title, style, date_hour, max_participants, description, actual_participants) VALUES (default,'El Fary', 'rock', '2023-01-12',  300,  'El fary ninio',  200)
INSERT INTO events( id, title, style, date_hour, max_participants, description, actual_participants) VALUES (default,'Las Ketchup', 'rock', '2023-01-12',  90,  'Asere Jeee',  80)
INSERT INTO events( id, title, style, date_hour, max_participants, description, actual_participants) VALUES (default,'Las Ketchup', 'rock', '2023-01-12',  90,  'Asere Jeee',  80)
INSERT INTO events( id, title, style, date_hour, max_participants, description, actual_participants) VALUES (default,'Las Ketchup', 'rock', '2023-01-12',  90,  'Asere Jeee',  80)
INSERT INTO users( id, username, password) VALUES (default,'Raul', '1234' ) 
INSERT INTO users( id, username, password) VALUES (default,'GobizConBambas', 'asas22' )
INSERT INTO users (id, username, password) VALUES(default, 'admin', '$2a$10$6wDeb3wqewh/nSWKVyIh5.0D4XjqyktJ5afuca0aBXDo1sUUIPDAO')
INSERT INTO roles (id, name) VALUES (default,'ROLE_ADMIN')
INSERT INTO roles (id, name) VALUES (default,'ROLE_USER')
INSERT INTO user_roles (user_id, role_id) VALUES (1,1)
